// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ChocoboManagement.Models
{
    public partial class Chocobo
    {
        public int Id { get; set; }
        public string ChocoboName { get; set; }
        public int Endurance { get; set; }
        public int Speed { get; set; }
        public int Strong { get; set; }
        public int? StableId { get; set; }

        public virtual Stable Stable { get; set; }
    }
}