// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ChocoboManagement.Models
{
    public partial class TrainerStable
    {
        public int TrainerId { get; set; }
        public int StableId { get; set; }

        public virtual Stable Stable { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}