// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ChocoboManagement.Models
{
    public partial class Trainer
    {
        public Trainer()
        {
            TrainerStables = new HashSet<TrainerStable>();
        }

        public int Id { get; set; }
        public string TrainerFirstname { get; set; }
        public string TrainerLastname { get; set; }

        public virtual ICollection<TrainerStable> TrainerStables { get; set; }
    }
}